### ISSUE TITLE
[译]Kotlin 1.1 Release Candidate is Here

### ISSUE THREAD

**Issue by ahong222** [enbandari/KotlinBlogTranslation#9]
Kotlin 1.1 Release Candidate is Here
https://github.com/enbandari/KotlinBlogTranslation/blob/master/original/Kotlin%201.1%20Release%20Candidate%20is%20Here.md
计划完成时间 05月04日

**Comment by pye52** [comment]
已完成

**Comment by bennyhuo** [comment]
好，这周末发
